_BASE_: "Base-SparseInst.yaml"
MODEL:
#   WEIGHTS: "pretrained_models/R-50.pkl"
  SPARSE_INST:
    DECODER:
      NUM_CLASSES: 25
      
DATASETS:
  # TRAIN: ("my_dataset_train",)
  TRAIN: ("my_dataset_val",)
  TEST:  ("my_dataset_val",)
SOLVER:
  IMS_PER_BATCH: 4
  MAX_ITER: 2000
  BASE_LR: 0.00005
TEST:
  EVAL_PERIOD: 500
OUTPUT_DIR: "output/sparse_inst_r50_giam"