_BASE_: "Base-SparseInst-Video.yaml"
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  STEPS: (7000, 14000)
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 2000
INPUT:
  CONTRASTIVE_LEARNING: True
  SAMPLING_FRAME_NUM: 2
  SAMPLING_FRAME_RANGE: 10
  SAMPLING_FRAME_RATIO: 2.0
  MIN_SIZE_TRAIN_SAMPLING: "choice_by_clip"
  RANDOM_FLIP: "flip_by_clip"
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 720
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  FORMAT: "RGB"
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
OUTPUT_DIR: "output/sparse_inst_r50_giam_contras"